# Generated by Django 4.1 on 2023-07-16 22:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='depot',
            fields=[
                ('name', models.CharField(max_length=50, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('mdp_windows', models.CharField(blank=True, default=None, max_length=50)),
                ('probleme', models.CharField(blank=True, default=None, max_length=500)),
                ('carton', models.BooleanField(default=False)),
                ('alimentation', models.BooleanField(default=False)),
                ('piece_a_modifier', models.CharField(blank=True, default=None, max_length=100)),
                ('reinitialisation', models.BooleanField(default=False)),
                ('ref_depot', models.CharField(max_length=50)),
                ('total_a_payer', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('numero_depot', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(2000)])),
                ('commentaire', models.CharField(blank=True, default=None, max_length=1000)),
                ('date', models.DateField(default=2020)),
                ('statut', models.CharField(choices=[('RC', 'Receptionné'), ('TR', 'En traitement'), ('TR', 'Terminé')], default='RC', max_length=100)),
                ('mail_envoyee', models.CharField(choices=[('RC', 'Receptionné'), ('TR', 'En traitement'), ('TR', 'Terminé')], default='RC', max_length=100)),
                ('first_name_seller', models.CharField(max_length=50)),
                ('last_name_seller', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('poste', models.CharField(choices=[('TC', 'Technicien'), ('CO', 'Commerciale')], default='CO', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
