# Generated by Django 4.1 on 2023-06-11 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fist_name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='depot',
            fields=[
                ('ref_depot', models.CharField(max_length=50)),
                ('total_a_payer', models.IntegerField()),
                ('numero_depot', models.IntegerField(default=1000, primary_key=True, serialize=False)),
                ('commentaire', models.CharField(default='', max_length=1000)),
                ('date', models.DateField(default=2020, validators=[django.core.validators.MinValueValidator(2020)])),
            ],
        ),
        migrations.CreateModel(
            name='ordinateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdp_windows', models.CharField(max_length=50)),
                ('probleme', models.CharField(max_length=500)),
                ('carton', models.BooleanField(default=False)),
                ('alimentation', models.BooleanField(default=False)),
                ('piece_a_modifier', models.CharField(max_length=100, null=True)),
                ('reinitialisation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='vendeur',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('fist_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('TC', 'Technicien'), ('CO', 'Commerciale')], max_length=5)),
                ('id', models.IntegerField(default=1000, primary_key=True, serialize=False)),
            ],
        ),
    ]
