# Generated by Django 4.1 on 2023-06-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordinateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdp_windows', models.CharField(max_length=50)),
                ('probleme', models.CharField(max_length=500)),
                ('carton', models.BooleanField(default=False)),
                ('alimentation', models.BooleanField(default=False)),
                ('piece_a_modifier', models.CharField(max_length=100, null=True)),
                ('reinitialisation', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ordinateurs',
        ),
        migrations.RenameModel(
            old_name='clients',
            new_name='client',
        ),
        migrations.AddField(
            model_name='ordinateur',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.client'),
        ),
        migrations.AddField(
            model_name='depot',
            name='ordinateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.ordinateur'),
        ),
    ]
