# Generated by Django 4.1 on 2023-06-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='numero_depot',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
