# Generated by Django 4.1 on 2023-06-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='commentaire',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='depot',
            name='mdp_windows',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='depot',
            name='piece_a_modifier',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='depot',
            name='probleme',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
    ]
