# Generated by Django 4.1 on 2023-06-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='poste',
            field=models.CharField(choices=[('TC', 'Technicien'), ('CO', 'Commerciale')], default='CO', max_length=100),
        ),
    ]
