# Generated by Django 4.2.5 on 2023-11-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='first_name_tech',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='depot',
            name='last_name_tech',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
