# Generated by Django 4.1 on 2023-06-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_customuser_poste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordinateur',
            name='proprietaire',
        ),
        migrations.DeleteModel(
            name='vendeur',
        ),
        migrations.RemoveField(
            model_name='depot',
            name='ordinateur',
        ),
        migrations.AddField(
            model_name='depot',
            name='alimentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='depot',
            name='carton',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='fist_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='mdp_windows',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='piece_a_modifier',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='probleme',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='reinitialisation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='depot',
            name='telephone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='client',
        ),
        migrations.DeleteModel(
            name='ordinateur',
        ),
    ]
