# Generated by Django 4.1 on 2023-07-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_depot_piece_modifiee_depot_type_de_prbl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depot',
            name='piece_modifiee',
        ),
        migrations.RemoveField(
            model_name='depot',
            name='type_de_prbl',
        ),
        migrations.AddField(
            model_name='depot',
            name='designation',
            field=models.CharField(choices=[('PO', 'Portable'), ('CO', 'Config'), ('AR', 'Article')], default='RC', max_length=100),
        ),
        migrations.AddField(
            model_name='depot',
            name='mode_envoi',
            field=models.CharField(choices=[('RE', 'Retrait'), ('EX', 'Expédition')], default='RC', max_length=100),
        ),
        migrations.AddField(
            model_name='depot',
            name='raison_retour',
            field=models.CharField(choices=[('DF', 'Defaut montage'), ('DP', 'Defaut produit'), ('PS', 'Defaut systeme'), ('PU', 'Probleme utilisateur'), ('PT', 'Probleme transport'), ('PC', 'Probleme compatibilite')], default='RC', max_length=100),
        ),
    ]
