# Generated by Django 4.2.3 on 2023-07-31 22:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_alter_depot_mail_envoyee_alter_depot_statut"),
        ("listings", "0003_remove_depot_piece_modifiee_and_more"),
    ]

    operations = []
