# Generated by Django 4.2.3 on 2023-08-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0004_merge_20230801_0002"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depot",
            name="commentaire",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="depot",
            name="designation",
            field=models.CharField(
                choices=[
                    ("", "---------"),
                    ("PO", "Laptop"),
                    ("CO", "Config"),
                    ("AR", "Article"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="depot",
            name="mail_envoyee",
            field=models.CharField(
                choices=[
                    ("", "---------"),
                    ("RC", "Receptionné"),
                    ("TR", "En traitement"),
                    ("TM", "Terminé"),
                ],
                default="RC",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="depot",
            name="mode_envoi",
            field=models.CharField(
                choices=[("", "---------"), ("RE", "Retrait"), ("EX", "Expédition")],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="depot",
            name="piece_a_modifier",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="depot",
            name="raison_retour",
            field=models.CharField(
                choices=[
                    ("", "---------"),
                    ("DF", "Defaut montage"),
                    ("DP", "Defaut produit"),
                    ("PS", "Defaut systeme"),
                    ("PU", "Probleme utilisateur"),
                    ("PT", "Probleme transport"),
                    ("PC", "Probleme compatibilite"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="depot",
            name="statut",
            field=models.CharField(
                choices=[
                    ("", "---------"),
                    ("RC", "Receptionné"),
                    ("TR", "En traitement"),
                    ("TM", "Terminé"),
                ],
                default="RC",
                max_length=100,
            ),
        ),
    ]
