# Generated by Django 4.1 on 2023-11-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_depot_commentaire_alter_depot_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depot',
            old_name='ref_depot',
            new_name='ref_commande',
        ),
    ]
