# Generated by Django 4.1 on 2023-11-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rename_ref_depot_depot_ref_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='probleme',
            field=models.TextField(blank=True, default=None, max_length=500),
        ),
    ]
